import { Entity } from '@dcl/schemas'
import { ILoggerComponent } from '@well-known-components/interfaces'
import * as path from 'path'
import * as fs from 'fs/promises'
import * as crypto from 'crypto'
import { AppComponents } from '../types'
import { ICacheStorageComponent } from '@dcl/core-commons'
import { normalizeContentsBaseUrl } from '../utils'
import { bufferExtensions, fileExtension, gltfExtensions, textureExtensions } from './extensions'
import { parseGltfDepRefs, resolveUriToContentFile } from './gltf-deps'
import { isS3NotFound } from './s3-helpers'

// Default TTL for Redis-stored asset probe hits. Canonical bundles are
// immutable, so a stale hit is harmless — but giving entries a finite lifetime
// keeps the Redis keyspace bounded across AB_VERSION bumps and lets evictions
// reclaim cache for cold content. Override via `redisTtlSeconds` on the
// `checkAssetCache` params.
const DEFAULT_REDIS_HIT_CACHE_TTL_SECONDS = 86_400

// Key prefix for the Redis-cached glb URI list. Distinct namespace from the
// probe hit-cache (which stores canonical S3 paths) so the two can never
// collide regardless of how the underlying redis cluster is shared.
const GLB_DEPS_CACHE_KEY_PREFIX = 'glb-deps:'

// Default TTL for Redis-stored glb URI parse results. Like the probe hit-cache,
// the value is a deterministic function of the glb's content hash (the URIs are
// inside the glb's own bytes), so a stale entry is harmless — TTL only governs
// how long the keyspace holds dead entries from no-longer-referenced glbs.
const DEFAULT_REDIS_GLB_DEPS_TTL_SECONDS = 86_400

// Silent logger used as the default in `computePerAssetDigests` when no
// logger is supplied — keeps existing callers (tests, the migrate script)
// from emitting unexpected log output after we added Redis-cache fallback
// warnings.
const NULL_LOGGER: ILoggerComponent.ILogger = {
  log: () => {},
  debug: () => {},
  info: () => {},
  warn: () => {},
  error: () => {}
}

// Re-export so callers still referencing `asset-reuse.ts` for this helper keep
// working. Single source of truth is `extensions.ts`.
export { fileExtension } from './extensions'

// Extensions whose bundles the converter actually uploads and we can therefore
// probe at the canonical prefix. `.bin` is deliberately absent: Unity never
// marks `.bin` files as their own asset bundles (`AssetBundleConverter.cs`
// `MarkAllAssetBundles` early-continues on `.bin`), so no `{hash}_{target}`
// object at the canonical prefix ever represents a buffer. Probing `.bin`
// hashes would just add S3 HEAD calls that always miss, and worse it would
// permanently block the full-cache short-circuit for every scene with a
// buffer file (which is most of them).
const PROBE_EXTENSIONS = new Set<string>([...gltfExtensions, ...textureExtensions])

// Unity-side extensions whose asset bundles have no inbound dependencies from
// other assets, so the converter can safely skip downloading & re-building
// them via the `-cachedHashes` flag when the canonical bundle already exists.
// Textures are intentionally excluded — they can still be referenced from
// within a non-cached GLTF during import, so we keep downloading them
// regardless of cache status. `.bin` is not here either: it never has a
// canonical bundle to hit in the first place (see PROBE_EXTENSIONS above).
const UNITY_SKIPPABLE_EXTENSIONS = new Set<string>([...gltfExtensions])

// Extensions that a `.glb` / `.gltf` bundle can reference as dependencies. The
// bundle output bytes embed the referenced dep bundle names (themselves derived
// from dep content hashes), so two scenes that share a glb source hash but
// differ in their dep set produce byte-different bundles — distinct canonical
// paths prevent cross-scene collision. Buffers ARE included here even though
// they're not probed directly: a `.gltf` (text) bundle's output DOES embed
// references to the buffer bundle Unity produces as part of the GLTF's own
// bundle, so the buffer hashes participate in the digest.
const GLB_DEP_EXTENSIONS = new Set<string>([...bufferExtensions, ...textureExtensions])

const GLTF_EXTENSIONS_SET = new Set<string>(gltfExtensions)

// Files whose bundle output is never read by the runtime — the launcher / world
// map UI fetches the raw bytes from the content server instead. Bundling them
// is dead work AND inflates the cache-miss counter when their content hash is
// per-deploy unique (e.g. SDK creator-hub captures a fresh thumbnail snapshot
// on every save). Listed here as path-regexes against `entry.file`.
//
// Defensive hardcoded list — covers cases the metadata-field walker below
// can't see (file dropped in the content map but not referenced from any
// metadata field). Append patterns here when a new SDK-generated metadata
// file with a predictable filename starts showing up.
const METADATA_ONLY_FILE_PATTERNS: RegExp[] = [/(?:^|\/)autogenerated-thumbnail\.png$/i]

// Dot-notation paths into `entity.metadata` whose VALUES (when present and
// string-typed) point at content-map files used as raw bytes by the launcher
// / world map UI only. Walked alongside `METADATA_ONLY_FILE_PATTERNS` so the
// classifier stays correct when the SDK adds new display fields with
// non-obvious filenames (e.g. a future `loadingScreen` field).
//
// IMPORTANT: only add a path here if the SDK / runtime never imports the
// referenced file as a Unity asset bundle. False positives produce a broken
// runtime (Unity-side null texture, magenta in client) and are hard to detect
// because the skip is silent. When in doubt, prefer NOT to add the field
// here and let Unity pay the build cost — the worst case is a missed
// optimisation, not a regression.
const METADATA_ONLY_METADATA_FIELDS: string[] = ['display.navmapThumbnail']

function readByPath(obj: any, dotPath: string): unknown {
  return dotPath.split('.').reduce<any>((acc, key) => (acc !== null && acc !== undefined ? acc[key] : undefined), obj)
}

/**
 * Set of content hashes Unity should NOT build asset bundles for because the
 * runtime never imports them — they're consumed as raw bytes by the launcher /
 * map UI. Combines two complementary sources:
 *
 *   (1) `METADATA_ONLY_FILE_PATTERNS` — hardcoded filename regexes for files
 *       known to be metadata-only regardless of how scene.json references
 *       them (covers SDK conventions like the creator-hub thumbnail).
 *   (2) `METADATA_ONLY_METADATA_FIELDS` — dot-paths into `entity.metadata`
 *       whose string values point at content-map files used as raw bytes
 *       only. Resolves the string to `entry.hash` via `entity.content`.
 *       Self-extending: new SDK fields just need a one-line addition to
 *       `METADATA_ONLY_METADATA_FIELDS`.
 *
 * Callers: (a) the probe loop in `checkAssetCache` skips these hashes so they
 * stay out of `cachedHashes` / `missingHashes` — keeps `ab_converter_asset_*`
 * counters honest. (b) `executeConversion` unions them into the
 * `-skippedHashes` CLI flag passed to Unity so the converter drops them from
 * `texturePaths` / `gltfPaths` before any download or import attempt.
 *
 * Conservative by design: a file is NEVER classified metadata-only on the
 * basis of CRDT / composite / index.js content. If a scene references the
 * navmap thumbnail from a runtime component too, this classification produces
 * a false negative (broken texture). For the fields currently in the list,
 * that case is implausible given SDK conventions, but the trade-off is
 * intentional — see the IMPORTANT comment on `METADATA_ONLY_METADATA_FIELDS`.
 */
export function findMetadataOnlyHashes(
  content: readonly { file: string; hash: string }[] | undefined,
  metadata: unknown
): ReadonlySet<string> {
  const hashes = new Set<string>()
  const entries = content ?? []

  // Case-insensitive index of content paths for the metadata-walker arm
  // below. Mirrors `computePerAssetDigests` (this file, ~line 846) which
  // also builds a `lowerCase(file) -> hash` map because the SDK / scene
  // authors don't consistently match the casing of references against the
  // content map (e.g. `assets/Images/Foo.PNG` vs `assets/images/foo.png`
  // resolve to the same asset at runtime). Building it inline here also
  // turns the per-field lookup from O(N) (Array.find) into O(1) — matters
  // if `METADATA_ONLY_METADATA_FIELDS` grows.
  const contentByLowerFile = new Map<string, string>()
  for (const entry of entries) {
    contentByLowerFile.set(entry.file.toLowerCase(), entry.hash)
    if (METADATA_ONLY_FILE_PATTERNS.some((re) => re.test(entry.file))) {
      hashes.add(entry.hash)
    }
  }

  if (metadata && typeof metadata === 'object') {
    for (const fieldPath of METADATA_ONLY_METADATA_FIELDS) {
      const value = readByPath(metadata, fieldPath)
      if (typeof value !== 'string') continue
      const hash = contentByLowerFile.get(value.toLowerCase())
      if (hash !== undefined) hashes.add(hash)
    }
  }

  return hashes
}

export type AssetCacheResult = {
  cachedHashes: string[]
  missingHashes: string[]
  // Hashes Unity can safely skip building. Subset of cachedHashes limited to file
  // extensions whose bundles have no inbound Unity dependencies from other assets.
  unitySkippableHashes: string[]
  // Composite-or-bare canonical bundle filename per content hash, so callers
  // (short-circuit manifest emit, post-Unity manifest append) don't have to
  // reconstruct the composite form.
  canonicalNameByHash: Record<string, string>
  // Per-glb/gltf deps digest — keyed by asset hash. Passed to Unity so it names
  // each glb/gltf bundle with the same composite key we probed and will upload to.
  // Non-glb entries (textures, buffers) don't appear in this map; their canonical
  // filename is hash-only.
  depsDigestByHash: ReadonlyMap<string, string>
  // Hashes the probe classified as metadata-only (raw-bytes display assets like
  // SDK creator-hub thumbnails or scene.json's navmap thumbnail). Returned so
  // `executeConversion` can union them into the `-skippedHashes` flag passed to
  // Unity without re-deriving from the entity. See `findMetadataOnlyHashes` for
  // the classification rules.
  metadataOnlyHashes: ReadonlySet<string>
}

/**
 * Deterministic digest of the entity's texture + buffer set. Folded into
 * glb/gltf canonical filenames so two scenes that share a glb source hash but
 * differ in deps land at distinct paths.
 *
 * Conservative superset — digests every texture/buffer in the entity, not just
 * the subset a specific glb actually references. Zero false-positive risk
 * (identical digest ⇒ identical dep set ⇒ identical Unity output). May miss
 * some cross-scene reuse when an entity carries loose non-glb textures; we
 * accept that trade-off.
 *
 * Sort is filename-primary, hash-secondary so it's stable regardless of
 * catalyst response order and robust to two different filenames sharing a hash.
 *
 * Exported for unit testing.
 */
export function computeDepsDigest(entityContent: ReadonlyArray<{ file: string; hash: string }>): string {
  const deps = entityContent.filter((e) => GLB_DEP_EXTENSIONS.has(fileExtension(e.file)))
  deps.sort((a, b) => (a.file < b.file ? -1 : a.file > b.file ? 1 : a.hash < b.hash ? -1 : a.hash > b.hash ? 1 : 0))
  // Feed JSON.stringify of the sorted tuple array rather than a hand-rolled
  // `${file}\t${hash}\n` concatenation so a filename that happens to contain a
  // tab or newline can't line-shift its neighbour's bytes into an identical
  // digest for a different dep set. DCL filenames are well-formed in practice,
  // but correctness shouldn't rely on that.
  const payload = JSON.stringify(deps.map((d) => [d.file, d.hash]))
  // 32 hex = 128-bit. Birthday-paradox collision probability at k tuples is
  // ~k² / 2·2¹²⁸ ≈ k² / 6.8·10³⁸. Even at 10¹⁸ tuples (astronomically
  // beyond any realistic DCL scale) the probability is ~10⁻³; at 10⁹ it's
  // ~10⁻²¹. The earlier version truncated to 16 hex (64-bit) which was
  // also safely above DCL's scale, but for critical-infrastructure
  // headroom this is essentially free — 16 extra chars in the filename at
  // rest, invisible to clients (who read the manifest opaquely) and
  // negligible in every downstream consumer.
  return crypto.createHash('sha256').update(payload).digest('hex').slice(0, 32)
}

/**
 * Build the canonical bundle filename Unity's output drops into
 * `{abVersion}/assets/{filename}`. glb/gltf filenames embed the per-asset
 * digest looked up from `depsDigestByHash`; BINs and textures are keyed by
 * hash alone (they're leaves with no inbound dep refs from their own bundle).
 *
 * Throws for glb/gltf hashes missing from the map — that would mean the caller
 * is probing an asset whose deps we haven't digested, and silently falling back
 * to a bare `{hash}_{target}` name would mis-align the probe key with the
 * filename Unity will emit. Missing digest for non-glb extensions is fine
 * (they're leaves; the map isn't expected to contain them).
 */
export function canonicalFilenameForAsset(
  hash: string,
  ext: string,
  target: string,
  depsDigestByHash: ReadonlyMap<string, string>
): string {
  if (GLTF_EXTENSIONS_SET.has(ext)) {
    const digest = depsDigestByHash.get(hash)
    if (!digest) throw new Error(`missing per-asset deps digest for glb/gltf hash ${hash}`)
    return `${hash}_${digest}_${target}`
  }
  return `${hash}_${target}`
}

/**
 * Sentinel value stored under each cached probe key. Content is irrelevant —
 * only the key's existence matters — but a non-empty string keeps the value
 * out of `JSON.parse` edge cases where `null`/`undefined` could be confused
 * with "key absent".
 */
const REDIS_HIT_MARKER = '1'

/**
 * Wraps `redis.get` so a Redis outage / transient failure is logged and
 * treated as a cache miss instead of failing the entire probe. Returns `true`
 * when the key is present (the stored value is the sentinel we wrote, no
 * point inspecting it — we control the writes).
 */
async function safeRedisHit(
  redis: ICacheStorageComponent,
  key: string,
  logger: ILoggerComponent.ILogger,
  metrics?: AppComponents['metrics']
): Promise<boolean> {
  try {
    const value = await redis.get<string>(key)
    return value !== null
  } catch (err: any) {
    // Warn-level: a Redis blip is recoverable and would otherwise look like a
    // silent cache-cold pod. Don't escalate to error — we don't want
    // dashboards lighting up red for routine reconnect cycles.
    logger.warn('redis hit-cache get failed; falling back to S3 HEAD for this key', {
      key,
      error: err?.message ?? String(err)
    } as any)
    if (metrics) {
      metrics.increment('ab_converter_redis_cache_errors_total', { operation: 'get', kind: 'probe-hit' })
    }
    return false
  }
}

/**
 * Wraps `redis.set` for write-through on S3 HEAD hits. Best-effort and
 * fire-and-forget at the call site — the probe result is already known by the
 * time we get here, so cache propagation latency must not be on the critical
 * path.
 */
async function safeRedisSet(
  redis: ICacheStorageComponent,
  key: string,
  ttlSeconds: number,
  logger: ILoggerComponent.ILogger,
  metrics?: AppComponents['metrics']
): Promise<void> {
  try {
    await redis.set(key, REDIS_HIT_MARKER, ttlSeconds)
  } catch (err: any) {
    logger.warn('redis hit-cache set failed; next probe for this key will refetch', {
      key,
      error: err?.message ?? String(err)
    } as any)
    if (metrics) {
      metrics.increment('ab_converter_redis_cache_errors_total', { operation: 'set', kind: 'probe-hit' })
    }
  }
}

/**
 * Wraps `redis.get` for the glb URI cache. On any Redis-side failure (network,
 * timeout, corrupted JSON) returns `null` and logs at warn level — the caller
 * falls through to the fetch + parse path. Never throws into the worker.
 */
async function safeRedisGetGlbDeps(
  redis: ICacheStorageComponent,
  glbHash: string,
  logger: ILoggerComponent.ILogger,
  metrics?: AppComponents['metrics']
): Promise<string[] | null> {
  try {
    return await redis.get<string[]>(`${GLB_DEPS_CACHE_KEY_PREFIX}${glbHash}`)
  } catch (err: any) {
    logger.warn('redis glb-deps cache get failed; falling back to catalyst fetch', {
      glbHash,
      error: err?.message ?? String(err)
    } as any)
    if (metrics) {
      metrics.increment('ab_converter_redis_cache_errors_total', { operation: 'get', kind: 'glb-deps' })
    }
    return null
  }
}

/**
 * Fire-and-forget write of a parsed glb result to Redis. Mirrors
 * {@link safeRedisSet} — propagation latency must not block the worker
 * returning its result to the caller.
 */
async function safeRedisSetGlbDeps(
  redis: ICacheStorageComponent,
  glbHash: string,
  value: string[],
  ttlSeconds: number,
  logger: ILoggerComponent.ILogger,
  metrics?: AppComponents['metrics']
): Promise<void> {
  try {
    await redis.set(`${GLB_DEPS_CACHE_KEY_PREFIX}${glbHash}`, value, ttlSeconds)
  } catch (err: any) {
    logger.warn('redis glb-deps cache set failed; subsequent probes will recompute', {
      glbHash,
      error: err?.message ?? String(err)
    } as any)
    if (metrics) {
      metrics.increment('ab_converter_redis_cache_errors_total', { operation: 'set', kind: 'glb-deps' })
    }
  }
}

/**
 * Extract the leading `{hash}` portion of a Unity-emitted bundle filename.
 *
 * Bundle filenames Unity emits look like `{hash}_{target}` optionally followed
 * by `.br` / `.manifest` / `.manifest.br`. Extracting the hash prefix lets
 * callers do an O(1) `Set.has` lookup against `cachedHashes` regardless of
 * which variant the file is.
 *
 * Returns `null` when the name doesn't follow the hash-prefixed convention —
 * for instance, generic Unity artifacts like `AssetBundles` / `AssetBundles.manifest`
 * that aren't content-addressed. Callers treat `null` as "not a cacheable
 * bundle" and leave the file alone.
 *
 * @param name - A filename from `readdir(outDirectory)` (no path, no slashes).
 * @returns The leading hash, or `null` for generic / unrecognized names.
 */
function extractHashFromBundleName(name: string): string | null {
  const underscore = name.indexOf('_')
  const dot = name.indexOf('.')
  // pick the earlier delimiter that is actually present
  const firstDelim = underscore < 0 ? dot : dot < 0 ? underscore : Math.min(underscore, dot)
  if (firstDelim <= 0) return null
  return name.substring(0, firstDelim)
}

/**
 * S3 HEAD probe that normalizes "not found" into `false` and surfaces every
 * other error. Uses `isS3NotFound` so the predicate is in one place.
 *
 * @param s3 - Configured AWS S3 client.
 * @param bucket - Bucket to probe.
 * @param key - Key to HEAD.
 * @returns `true` if the object exists, `false` on 404.
 * @throws Any non-404 error reaching the SDK (500, auth failure, etc.).
 */
async function headExists(s3: AppComponents['cdnS3'], bucket: string, key: string): Promise<boolean> {
  try {
    await s3.headObject({ Bucket: bucket, Key: key }).promise()
    return true
  } catch (err: unknown) {
    if (isS3NotFound(err)) return false
    throw err
  }
}

/**
 * Array-map with bounded concurrency — runs `fn` over every element of `items`
 * in parallel with at most `concurrency` in-flight promises at a time. Results
 * come back in the same order as `items`.
 *
 * Used to bound S3 HEAD probes in the per-asset cache, S3 `CopyObject` calls in
 * the migration script, and parallel `fs.unlink` calls in the purge step —
 * enough to saturate throughput without exhausting the default HTTPS agent pool
 * or hitting the container's `ulimit -n` on low-limit hosts.
 *
 * If `fn` rejects for any item, the whole promise rejects on first failure
 * (Promise.all semantics). Workers already in flight for other items keep
 * running until natural completion — their results are discarded. Clamps
 * `concurrency` to at least 1 so a caller accidentally passing 0 doesn't
 * return an array of holes.
 *
 * @param items - Inputs to process.
 * @param concurrency - Maximum number of simultaneous `fn` invocations.
 * @param fn - Per-item worker. Called with each element of `items`.
 * @returns Array of results in input order.
 */
export async function mapBounded<T, R>(items: T[], concurrency: number, fn: (item: T) => Promise<R>): Promise<R[]> {
  if (items.length === 0) return []
  const results: R[] = new Array(items.length)
  let cursor = 0

  async function worker() {
    while (true) {
      const idx = cursor++
      if (idx >= items.length) return
      results[idx] = await fn(items[idx])
    }
  }

  // Clamp to at least 1 so a caller accidentally passing 0 doesn't leave the
  // returned array full of holes.
  const workerCount = Math.min(Math.max(1, concurrency), items.length)
  await Promise.all(Array.from({ length: workerCount }, () => worker()))
  return results
}

/**
 * Fetcher function used by `computePerAssetDigests` to pull glb/gltf bytes
 * from the catalyst. Kept as a plain parameter (rather than a component
 * dependency) so tests can swap in a memory-backed fetcher without mocking
 * global fetch.
 */
export type GltfFetcher = (url: string, ext: '.glb' | '.gltf') => Promise<Buffer>

// 256 MB upper bound on a single glb/gltf download. Defence-in-depth against
// a malicious or corrupted catalyst entry that declares an unbounded body —
// without this, `arrayBuffer()` would buffer the whole response before we see
// it. DCL's largest legitimate glbs are ~tens of MB, so 256 is generous
// headroom without risking an OOM on the conversion worker.
const MAX_GLTF_DOWNLOAD_BYTES = 256 * 1024 * 1024
const GLB_JSON_START = 20
const GLTF_FETCH_ATTEMPTS = 3
const GLTF_FETCH_RETRY_BASE_MS = 250
// Upper bound on a server-supplied `Retry-After`. A catalyst that asks us to
// wait longer than this is effectively broken for our use case — SQS visibility
// timeout will retry the whole job sooner, and blocking here just hogs a worker
// slot. We cap and let the next attempt (or SQS) handle it.
const MAX_RETRY_AFTER_MS = 30_000

type FetchResponse = {
  ok: boolean
  status: number
  statusText: string
  headers: { get(name: string): string | null }
  body?: ReadableStream<Uint8Array> | null
  arrayBuffer(): Promise<ArrayBuffer>
}

class NonRetryableFetchError extends Error {}
class RetryableFetchError extends Error {
  /** Server-supplied hint (from `Retry-After`) parsed into ms. When set,
   * `withFetchRetries` uses this instead of its exponential-backoff formula
   * — the catalyst knows better than we do how long to wait under 429/503. */
  retryAfterMs?: number
  constructor(message: string, retryAfterMs?: number) {
    super(message)
    this.retryAfterMs = retryAfterMs
  }
}

/**
 * Parse an HTTP `Retry-After` value into milliseconds, clamped to
 * `[0, MAX_RETRY_AFTER_MS]`. RFC 7231 allows two forms:
 *   - delta-seconds (e.g. `"120"`) — by far the most common from catalysts.
 *   - HTTP-date (e.g. `"Wed, 21 Oct 2026 07:28:00 GMT"`) — rarer; clamped
 *     against `now` so a clock skew doesn't produce a negative delay.
 *
 * Returns `undefined` when the header is absent or unparseable — the caller
 * (`withFetchRetries`) then falls back to its exponential-backoff formula.
 * We intentionally don't surface parse errors: a malformed Retry-After is a
 * catalyst bug, not a reason to fail the whole fetch.
 *
 * Exported for unit testing.
 */
export function parseRetryAfterMs(raw: string | null): number | undefined {
  if (raw === null) return undefined
  const trimmed = raw.trim()
  if (trimmed === '') return undefined

  // delta-seconds: ASCII digits only. `Number('120abc')` would happily parse
  // to NaN here, but `Number('120')` → 120 and `Number('')` → 0, so we need
  // an explicit digits-only check to distinguish "0 seconds" from "not a
  // number".
  if (/^\d+$/.test(trimmed)) {
    const seconds = Number(trimmed)
    return Math.min(Math.max(0, seconds * 1000), MAX_RETRY_AFTER_MS)
  }

  // Anything remaining must be an HTTP-date — those always contain at least
  // one letter (weekday / month abbreviation). Without this check,
  // `Date.parse("-1")` silently succeeds (epoch-ish), and `Date.parse("1.5")`
  // would slip through on some engines, returning a misleading 0ms delta for
  // what is actually a malformed numeric value.
  if (!/[a-zA-Z]/.test(trimmed)) return undefined

  const dateMs = Date.parse(trimmed)
  if (Number.isNaN(dateMs)) return undefined
  const delta = dateMs - Date.now()
  return Math.min(Math.max(0, delta), MAX_RETRY_AFTER_MS)
}

/**
 * Read the declared `Content-Length` header as a number, or `-1` when absent.
 */
function contentLength(res: { headers: { get(name: string): string | null } }): number {
  return Number(res.headers.get('content-length') ?? '-1')
}

/**
 * Convert a full response body into a `Buffer` and enforce the download guard.
 */
async function responseBytes(url: string, res: { arrayBuffer(): Promise<ArrayBuffer> }): Promise<Buffer> {
  const bytes = Buffer.from(await res.arrayBuffer())
  if (bytes.length > MAX_GLTF_DOWNLOAD_BYTES) {
    throw new NonRetryableFetchError(
      `glb/gltf at ${url} buffered ${bytes.length} bytes > ${MAX_GLTF_DOWNLOAD_BYTES} (refusing to buffer)`
    )
  }
  return bytes
}

/**
 * Fail fast on non-2xx HTTP responses, classifying retryable status codes.
 *
 * For retryable statuses we also propagate any `Retry-After` hint into the
 * thrown error so `withFetchRetries` can respect the catalyst's preferred
 * backoff — important under sustained 429s where our fixed jitter formula
 * would hammer a cooperating server.
 */
function assertOkResponse(url: string, res: FetchResponse): void {
  if (!res.ok) {
    const message = `failed to fetch ${url}: ${res.status} ${res.statusText}`
    if (res.status === 408 || res.status === 429 || res.status >= 500) {
      const retryAfterMs = parseRetryAfterMs(res.headers.get('retry-after'))
      throw new RetryableFetchError(message, retryAfterMs)
    }
    throw new NonRetryableFetchError(message)
  }
}

/**
 * Reject responses whose declared payload length exceeds the download guard.
 */
function assertDeclaredLengthWithinGuard(url: string, res: FetchResponse): void {
  const declaredLength = contentLength(res)
  if (Number.isFinite(declaredLength) && declaredLength > MAX_GLTF_DOWNLOAD_BYTES) {
    throw new NonRetryableFetchError(
      `glb/gltf at ${url} declared Content-Length ${declaredLength} > ${MAX_GLTF_DOWNLOAD_BYTES} (refusing to buffer)`
    )
  }
}

/**
 * Require a valid `Content-Length` header when the response has no stream body.
 */
function requireFallbackContentLength(url: string, res: FetchResponse): void {
  const declaredLength = contentLength(res)
  if (!Number.isFinite(declaredLength) || declaredLength < 0) {
    throw new NonRetryableFetchError(`glb/gltf at ${url} has no stream body and no valid Content-Length guard`)
  }
  if (declaredLength > MAX_GLTF_DOWNLOAD_BYTES) {
    throw new NonRetryableFetchError(
      `glb/gltf at ${url} declared Content-Length ${declaredLength} > ${MAX_GLTF_DOWNLOAD_BYTES} (refusing to buffer)`
    )
  }
}

/**
 * Convert a Web stream chunk into a zero-copy `Buffer` view.
 */
function toBuffer(chunk: Uint8Array): Buffer {
  return Buffer.from(chunk.buffer, chunk.byteOffset, chunk.byteLength)
}

/**
 * Sleep for the requested number of milliseconds.
 */
async function sleep(ms: number): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, ms))
}

/**
 * Compute exponential backoff with jitter for GLB/GLTF retries.
 */
function retryDelayMs(attempt: number): number {
  const jitter = Math.floor(Math.random() * GLTF_FETCH_RETRY_BASE_MS)
  return GLTF_FETCH_RETRY_BASE_MS * Math.pow(2, attempt) + jitter
}

/**
 * Treat every fetch error except the explicit non-retryable wrapper as retryable.
 */
function isRetryableFetchError(err: unknown): boolean {
  return !(err instanceof NonRetryableFetchError)
}

/**
 * Fetch and fully buffer a GLTF/GLB response when no prefix-only optimization applies.
 */
async function fetchFullWithContentLengthGuard(url: string, res: FetchResponse): Promise<Buffer> {
  assertOkResponse(url, res)
  assertDeclaredLengthWithinGuard(url, res)
  if (res.body) return readWholeStream(url, res)

  requireFallbackContentLength(url, res)
  return responseBytes(url, res)
}

/**
 * Stream a full response body into memory with a hard upper bound.
 *
 * When the response declares a `Content-Length`, we treat a stream that ends
 * with fewer bytes than declared as a transport-level truncation and throw
 * `RetryableFetchError` so `withFetchRetries` re-issues the request. Symmetric
 * with the truncation check in `readGlbJsonPrefix` for `.glb` — a catalyst/CDN
 * connection drop mid-body isn't a content defect, the bytes at this hash are
 * unchanged. Chunked responses without a declared length can't be checked
 * this way (we have no expected total to compare against), so we accept
 * whatever drained; the burden then falls on the downstream parser to detect
 * structural defects from the partial bytes.
 *
 * `assertDeclaredLengthWithinGuard` has already enforced the upper bound on
 * the declared length, so any value reaching this check is in `[0, MAX]`.
 */
async function readWholeStream(url: string, res: FetchResponse): Promise<Buffer> {
  if (!res.body) throw new RetryableFetchError(`glb/gltf at ${url} returned no response body stream`)

  const declaredLength = contentLength(res)
  const expectedTotal = Number.isFinite(declaredLength) && declaredLength >= 0 ? declaredLength : undefined

  const reader = res.body.getReader()
  const chunks: Buffer[] = []
  let total = 0

  try {
    while (true) {
      const { done, value } = await reader.read()
      if (done) break
      const bytes = toBuffer(value)
      total += bytes.length
      if (total > MAX_GLTF_DOWNLOAD_BYTES) {
        throw new NonRetryableFetchError(
          `glb/gltf at ${url} streamed ${total} bytes > ${MAX_GLTF_DOWNLOAD_BYTES} (refusing to buffer)`
        )
      }
      chunks.push(bytes)
    }
  } catch (err: any) {
    try {
      await reader.cancel()
    } catch (_cancelErr: any) {}
    throw err
  } finally {
    reader.releaseLock()
  }

  if (expectedTotal !== undefined && total < expectedTotal) {
    throw new RetryableFetchError(
      `glb/gltf at ${url} ended after ${total} bytes, before declared Content-Length ${expectedTotal}`
    )
  }

  return Buffer.concat(chunks, total)
}

/**
 * Stream only the JSON prefix needed from a GLB, then cancel the response body.
 */
async function readGlbJsonPrefix(url: string, res: FetchResponse): Promise<Buffer> {
  assertOkResponse(url, res)
  if (!res.body) {
    requireFallbackContentLength(url, res)
    return responseBytes(url, res)
  }

  const reader = res.body.getReader()
  const chunks: Buffer[] = []
  let total = 0
  let targetBytes: number | undefined

  try {
    while (true) {
      const { done, value } = await reader.read()
      if (done) break
      const bytes = toBuffer(value)
      const remaining = targetBytes === undefined ? bytes.length : Math.max(0, targetBytes - total)
      const kept = remaining >= bytes.length ? bytes : bytes.subarray(0, remaining)

      if (kept.length > 0) {
        chunks.push(kept)
        total += kept.length
      }

      if (targetBytes === undefined && total >= GLB_JSON_START) {
        const prefix = Buffer.concat(chunks, total)
        const jsonChunkLength = prefix.readUInt32LE(12)
        targetBytes = GLB_JSON_START + jsonChunkLength
        if (targetBytes > MAX_GLTF_DOWNLOAD_BYTES) {
          throw new NonRetryableFetchError(
            `glb/gltf at ${url} JSON chunk ${targetBytes} > ${MAX_GLTF_DOWNLOAD_BYTES} (refusing to buffer)`
          )
        }
      }

      if (targetBytes !== undefined && total >= targetBytes) {
        await reader.cancel()
        return Buffer.concat(chunks, targetBytes)
      }
    }
  } catch (err: any) {
    try {
      await reader.cancel()
    } catch (_cancelErr: any) {}
    throw err
  } finally {
    reader.releaseLock()
  }

  // A stream that ends before the JSON chunk is complete is a transport-level
  // truncation (catalyst/CDN dropped the connection mid-body), not a content
  // defect: the underlying glb at this hash is unchanged. Throwing
  // `RetryableFetchError` lets `withFetchRetries` re-issue the request — a
  // single CDN burp no longer collapses the digest pass and pins the entity
  // under a permanent `_failed.json` sentinel in `executeConversion`.
  throw new RetryableFetchError(
    targetBytes === undefined
      ? `glb/gltf at ${url} ended before the 20-byte GLB JSON header was available`
      : `glb/gltf at ${url} ended after ${total} bytes, before JSON chunk end ${targetBytes}`
  )
}

/**
 * Retry a fetch operation on retryable HTTP or stream failures. When the error
 * carries a parsed `Retry-After` hint (populated by `assertOkResponse` on
 * 408/429/503 responses), the hint wins over our exponential-backoff formula
 * — a cooperating catalyst knows better than we do how long to back off.
 *
 * The callback receives the zero-based `attempt` number so it can vary its
 * request between tries — `defaultGltfFetcher` uses this to add a cachebust
 * query param on retries that bypasses CDN caches.
 */
async function withFetchRetries<T>(fn: (attempt: number) => Promise<T>): Promise<T> {
  let lastError: unknown
  for (let attempt = 0; attempt < GLTF_FETCH_ATTEMPTS; attempt++) {
    try {
      return await fn(attempt)
    } catch (err: unknown) {
      lastError = err
      if (attempt === GLTF_FETCH_ATTEMPTS - 1 || !isRetryableFetchError(err)) throw err
      const hint = err instanceof RetryableFetchError ? err.retryAfterMs : undefined
      await sleep(hint ?? retryDelayMs(attempt))
    }
  }
  throw lastError
}

/**
 * Append a `_retry={attempt}` query parameter to a fetch URL so it bypasses
 * any intermediate CDN cache (Cloudflare, CloudFront) by changing the cache
 * key. Catalyst content endpoints are keyed only by the CID in the path and
 * ignore unknown query parameters, so this is a transparent transform on the
 * server side; from the CDN's point of view it's a fresh URL that triggers a
 * MISS and a pull from origin.
 */
function withRetryQueryParam(url: string, attempt: number): string {
  const u = new URL(url)
  u.searchParams.set('_retry', String(attempt))
  return u.toString()
}

/**
 * Default fetcher — wraps native fetch with a non-ok status check, retries,
 * a Content-Length guard, and streaming reads. Binary GLBs are only streamed
 * through the embedded JSON chunk; text GLTFs are fully streamed because the
 * dependency refs can appear anywhere in the JSON document.
 *
 * Uses `arrayBuffer()` only as a guarded fallback for mocked / non-standard
 * responses that do not expose a stream body.
 *
 * Retries past attempt 0 add `?_retry={attempt}` to force a CDN MISS. A
 * one-off transient short-read on attempt 0 is recoverable by hitting the
 * same cache entry again, but a *deterministic* short-read is most often a
 * poisoned CDN cache fill that will replay the broken body to every request
 * landing on the same edge POP. Without the cachebust the retry just re-reads
 * the same corrupted cached bytes and gives up after exhausting attempts;
 * with it, the second attempt forces a fresh origin pull, the cache refills
 * with a clean body, and subsequent workers benefit too (broken object
 * effectively gets evicted).
 */
async function defaultGltfFetcher(url: string, ext: '.glb' | '.gltf'): Promise<Buffer> {
  return withFetchRetries(async (attempt) => {
    const fetchUrl = attempt === 0 ? url : withRetryQueryParam(url, attempt)
    const init = ext === '.glb' ? { headers: { 'Accept-Encoding': 'identity' } } : undefined
    const res = (await fetch(fetchUrl, init)) as FetchResponse
    // Error messages from the readers carry the URL — pass the original
    // (without `?_retry=N`) so production logs and sentry triage stay
    // grep-able by content hash and aren't fragmented by retry-attempt
    // variants of the same logical URL.
    return ext === '.glb' ? readGlbJsonPrefix(url, res) : fetchFullWithContentLengthGuard(url, res)
  })
}

/**
 * Reason a glb/gltf was excluded from the digest map. `missing-deps` covers
 * the common production case where the glb references a texture/buffer URI
 * that is not present in the entity's `content` map — Unity can't resolve
 * the dependency either, so attempting conversion would fail. `unparseable`
 * covers structural defects in the glb itself (bad magic, truncated JSON
 * chunk, non-object root, URI escapes that violate the resolver's rules) —
 * Unity wouldn't be able to import it either.
 *
 * Both reasons are content-deterministic: re-running against the same entity
 * always produces the same skip set, so workers don't flap on retry.
 */
export type SkipReason = 'missing-deps' | 'unparseable'

export type SkippedAsset = {
  hash: string
  file: string
  reason: SkipReason
  /** Human-readable detail for log/metric inspection — first missing URI for
   * `missing-deps`, the parse/resolve error message for `unparseable`. Never
   * read programmatically; freeform text. Truncated at construction (see
   * `MAX_SKIP_DETAIL_LENGTH`) so a glb carrying a pathologically large URI
   * inside its embedded JSON can't blow the size of the warn-log line that
   * embeds these as `samples` — structured-log backends typically reject or
   * silently drop fields above ~10 KB, and even short of that a 50 KB
   * payload from a misbehaving exporter would dominate triage logs. */
  detail?: string
}

/**
 * Upper bound on the length of `SkippedAsset.detail`. Picked empirically:
 * the longest legitimate detail is `'glTF URI "<uri>" -> "<resolved>"'` for
 * a `missing-deps` skip; real DCL entity paths and URIs are well under 100
 * chars apiece, so 256 keeps the realistic message intact while still
 * fitting comfortably under common structured-log field limits when five
 * of these land in a single warn-log entry.
 */
export const MAX_SKIP_DETAIL_LENGTH = 256
export const SKIP_DETAIL_TRUNCATION_MARKER = '…(truncated)'

/**
 * Strip ASCII control chars (NUL through US, plus DEL) before truncating.
 * A glb URI carrying a literal `\n` / `\r` could inject phantom lines into
 * plaintext log backends, and some structured-log shippers crash on raw
 * control chars. JSON encoders already escape these, so this is strictly
 * defense-in-depth — but it's cheap and the field is freeform diagnostic
 * text where there's no legitimate reason for control chars to appear.
 */
function truncateSkipDetail(s: string): string {
  // eslint-disable-next-line no-control-regex
  const sanitized = s.replace(/[\x00-\x1f\x7f]/g, ' ')
  if (sanitized.length <= MAX_SKIP_DETAIL_LENGTH) return sanitized
  return sanitized.slice(0, MAX_SKIP_DETAIL_LENGTH) + SKIP_DETAIL_TRUNCATION_MARKER
}

export type PerAssetDigestResult = {
  digests: ReadonlyMap<string, string>
  skipped: ReadonlyMap<string, SkippedAsset>
}

/**
 * Compute a per-glb/gltf deps digest for every gltf-extension asset in the
 * entity. For each glb/gltf: download the bytes, parse the embedded JSON to
 * enumerate its external URI refs, resolve each URI against `entity.content`
 * to get the `{file, hash}` tuples the glb actually depends on, and hash
 * that subset through `computeDepsDigest`.
 *
 * Two glbs with identical referenced dep sets (same file names, same content
 * hashes) produce identical digests regardless of ordering inside the glTF
 * JSON — guaranteed by `parseGltfDepRefs` dedup+sort on the way in and by
 * `computeDepsDigest`'s own sort. Two glbs whose dep sets differ in any entry
 * produce distinct digests.
 *
 * Returns `{ digests, skipped }`. A glb that references a URI absent from
 * `entity.content`, or whose bytes are structurally malformed, lands in
 * `skipped` instead of `digests` — the caller is expected to forward those
 * hashes to Unity so they're not converted (the bundle they'd produce can't
 * render in-world anyway). Catalyst fetch failures keep their throw
 * semantics: those are transient network conditions where retrying via SQS
 * is the right response, not a content defect.
 */
export async function computePerAssetDigests(
  entity: Pick<Entity, 'content'>,
  contentServerUrl: string,
  options?: {
    fetcher?: GltfFetcher
    concurrency?: number
    aggregateTimeoutMs?: number
    /** Optional shared Redis cache for parsed glb URIs. When supplied, each
     * glb's URI list is looked up by hash BEFORE the catalyst byte fetch;
     * on hit the fetch + JSON parse are skipped and we go straight to
     * URI-resolution against `entity.content`. Hash uniquely identifies the
     * glb bytes, so the cached URIs are valid across entities and pods —
     * different entities referencing the same glb hash share the lookup. */
    redis?: ICacheStorageComponent
    /** TTL for Redis-cached URI entries. Defaults to
     * {@link DEFAULT_REDIS_GLB_DEPS_TTL_SECONDS}. Ignored when no redis is
     * supplied. */
    redisTtlSeconds?: number
    /** Logger used by the glb-deps cache helpers for warn-level fallback
     * messages on Redis errors. Defaults to a silent no-op so existing
     * callers (tests, migrate script) don't see unexpected output. */
    logger?: ILoggerComponent.ILogger
    /** Metrics component for cache outcome counters. Optional — when unset,
     * the cache still works, only the observability disappears. */
    metrics?: AppComponents['metrics']
    /** Build target / AB version label values, passed through to metrics. */
    metricLabels?: { build_target: string; ab_version: string }
  }
): Promise<PerAssetDigestResult> {
  const fetcher = options?.fetcher ?? defaultGltfFetcher
  // 20 in-flight catalyst fetches — below the S3 HEAD probe concurrency (50)
  // because catalyst fetches are heavier and more rate-limit-sensitive, but
  // high enough to amortize TCP/TLS setup across a scene with dozens of glbs.
  const concurrency = options?.concurrency ?? 20
  // Aggregate wall-clock cap on the entire digest pass. Per-fetch retries are
  // already bounded (3 attempts × ≤30 s Retry-After cap), but a scene with
  // dozens of glbs each retrying could compound to several minutes — past the
  // SQS visibility window the worker is otherwise expected to respect. The
  // timeout fires reject; in-flight fetches are not actively cancelled (their
  // sockets close on their own when the worker finally moves on), so the
  // process doesn't hang on lingering tasks. Default undefined keeps the
  // public API non-breaking — callers opt in.
  const aggregateTimeoutMs = options?.aggregateTimeoutMs
  const redis = options?.redis
  const redisTtlSeconds = options?.redisTtlSeconds ?? DEFAULT_REDIS_GLB_DEPS_TTL_SECONDS
  const logger = options?.logger ?? NULL_LOGGER
  const metrics = options?.metrics
  const metricLabels = options?.metricLabels

  const content = entity.content ?? []
  // Case-insensitive lookup: glTF URIs and entity content-map paths may
  // differ only in casing (e.g. "Floor03_Normal.png" vs "Floor03_normal.png").
  // macOS/Windows file systems paper over this, so Unity converts fine — but a
  // strict Map.get() would falsely mark the dep as missing. Lowercasing keys
  // mirrors the case-insensitive resolution Unity relies on.
  const contentByFile = new Map<string, string>()
  for (const c of content) contentByFile.set(c.file.toLowerCase(), c.hash)

  const contentsBaseUrl = normalizeContentsBaseUrl(contentServerUrl)

  const gltfEntries = content.filter((e) => GLTF_EXTENSIONS_SET.has(fileExtension(e.file)))
  const digests = new Map<string, string>()
  const skipped = new Map<string, SkippedAsset>()
  if (gltfEntries.length === 0) return { digests, skipped }

  type WorkerResult = { kind: 'ok'; hash: string; digest: string } | { kind: 'skip'; skip: SkippedAsset }

  const work = mapBounded<(typeof gltfEntries)[number], WorkerResult>(
    gltfEntries,
    concurrency,
    async (entry): Promise<WorkerResult> => {
      const ext = fileExtension(entry.file) as '.glb' | '.gltf'

      // Redis cache lookup: the URI list is a deterministic function of the
      // glb bytes (and therefore of its content hash), so we can skip the
      // catalyst byte fetch + JSON parse on hit. Parse failures are NOT
      // cached — they're rare and `ab_converter_glb_skipped_total{reason}`
      // already tracks the rate. `missing-deps` skips can't be cached either:
      // they depend on the entity content map, which varies per-entity.
      let uris: string[] | undefined
      if (redis) {
        const cached = await safeRedisGetGlbDeps(redis, entry.hash, logger, metrics)
        if (cached !== null) {
          if (metrics && metricLabels) {
            metrics.increment('ab_converter_glb_deps_cache_total', { ...metricLabels, outcome: 'hit' })
          }
          uris = cached
        }
      }

      if (uris === undefined) {
        if (metrics && metricLabels && redis) {
          metrics.increment('ab_converter_glb_deps_cache_total', { ...metricLabels, outcome: 'miss' })
        }
        // Fetch errors stay throws — they're transient and bubble up to
        // `executeConversion` where they trigger SQS retry. Only content-
        // determined defects (parse + resolve) become skips.
        const bytes = await fetcher(`${contentsBaseUrl}${entry.hash}`, ext)

        try {
          uris = parseGltfDepRefs(bytes, ext)
        } catch (err: any) {
          // Parse failure: skip but do NOT cache. The next probe will refetch
          // and re-fail consistently; the cost is bounded by how rare
          // structurally broken glbs are in practice. Not caching keeps the
          // cache value shape narrow (just URI lists) and ensures any future
          // parser improvement takes effect immediately rather than waiting
          // for the TTL to elapse on cached negatives.
          return {
            kind: 'skip',
            skip: {
              hash: entry.hash,
              file: entry.file,
              reason: 'unparseable',
              detail: truncateSkipDetail(err?.message ?? String(err))
            }
          }
        }

        // Successful parse — write the URI list back to Redis for the next
        // probe. Fire-and-forget; the caller's result doesn't depend on
        // propagation.
        if (redis) {
          void safeRedisSetGlbDeps(redis, entry.hash, uris, redisTtlSeconds, logger, metrics)
        }
      }

      // Resolve URIs against entity content, dedup on (file, hash) — the glTF
      // URI layer already dedups by URI, but two distinct URIs could resolve to
      // the same content file via percent-encoding variants or path aliases.
      const seen = new Set<string>()
      const deps: Array<{ file: string; hash: string }> = []
      for (const uri of uris) {
        let resolved: string
        try {
          resolved = resolveUriToContentFile(uri, entry.file)
        } catch (err: any) {
          // Bad percent-encoding / scheme / escapes-root URIs are still
          // structural defects in the glTF — Unity wouldn't accept them
          // either. Treat as `unparseable` rather than `missing-deps` so
          // operators can distinguish "content team published a broken
          // entity" (missing deps) from "exporter emitted a malformed URI"
          // (unparseable) at the metric layer. The thrown message embeds
          // the offending URI string verbatim, which is content-controlled —
          // truncate before storing so a multi-KB URI can't poison logs.
          return {
            kind: 'skip',
            skip: {
              hash: entry.hash,
              file: entry.file,
              reason: 'unparseable',
              detail: truncateSkipDetail(err?.message ?? String(err))
            }
          }
        }
        const hash = contentByFile.get(resolved.toLowerCase())
        if (!hash) {
          return {
            kind: 'skip',
            skip: {
              hash: entry.hash,
              file: entry.file,
              reason: 'missing-deps',
              detail: truncateSkipDetail(`"${uri}" -> "${resolved}"`)
            }
          }
        }
        const key = `${resolved}\0${hash}`
        if (seen.has(key)) continue
        seen.add(key)
        deps.push({ file: resolved, hash })
      }

      return { kind: 'ok', hash: entry.hash, digest: computeDepsDigest(deps) }
    }
  )

  let timer: ReturnType<typeof setTimeout> | undefined
  let results: WorkerResult[]
  try {
    if (aggregateTimeoutMs && aggregateTimeoutMs > 0) {
      const timeoutPromise = new Promise<never>((_, reject) => {
        timer = setTimeout(
          () =>
            reject(
              new Error(
                `Per-asset digest computation exceeded ${aggregateTimeoutMs}ms aggregate timeout (${gltfEntries.length} glb/gltf assets)`
              )
            ),
          aggregateTimeoutMs
        )
      })
      results = await Promise.race([work, timeoutPromise])
    } else {
      results = await work
    }
  } finally {
    if (timer !== undefined) clearTimeout(timer)
  }

  for (const r of results) {
    if (r.kind === 'ok') digests.set(r.hash, r.digest)
    else skipped.set(r.skip.hash, r.skip)
  }
  return { digests, skipped }
}

type CheckAssetCacheParams = {
  // Both `content` AND `metadata` are required: the metadata walker in
  // `findMetadataOnlyHashes` reads dot-paths from `entity.metadata` (e.g.
  // `display.navmapThumbnail`) to classify content entries as raw-bytes-only.
  // Narrowing this to `Pick<Entity, 'content'>` would let `findMetadataOnlyHashes`
  // compile but silently degrade to the hardcoded-pattern arm only, because
  // `entity.metadata` would be missing at runtime.
  entity: Pick<Entity, 'content' | 'metadata'>
  abVersion: string
  buildTarget: string
  cdnBucket: string
  concurrency?: number
  /** Pre-computed per-asset deps digests keyed by asset hash. When supplied,
   * skips the re-computation that would otherwise happen inside
   * `checkAssetCache`. Callers that also need the digests (e.g. to pass to
   * Unity independently of whether the probe succeeded) should compute once
   * and pass through. Required in practice because computing digests involves
   * downloading glb bytes — the caller already has a catalyst URL in context. */
  depsDigestByHash?: ReadonlyMap<string, string>
  /** Catalyst URL used to download glb/gltf bytes when `depsDigestByHash` is
   * not supplied. Ignored when `depsDigestByHash` is provided. */
  contentServerUrl?: string
  /** Injectable fetcher for glb bytes — forwarded to `computePerAssetDigests`. */
  fetcher?: GltfFetcher
  /** TTL applied to Redis-stored hit-cache entries. Defaults to
   * {@link DEFAULT_REDIS_HIT_CACHE_TTL_SECONDS}. Ignored when no Redis component
   * is supplied (or when its `set` is a no-op). */
  redisTtlSeconds?: number
}

/**
 * Probe the canonical `{abVersion}/assets/{hash}_{buildTarget}` prefix for each valid
 * asset hash in the entity. Returns the partition of hashes (cached vs missing) plus
 * the subset of cached hashes whose file extension is safe to skip on the Unity side.
 */
export async function checkAssetCache(
  components: Pick<AppComponents, 'cdnS3' | 'logs' | 'metrics' | 'redis'>,
  params: CheckAssetCacheParams
): Promise<AssetCacheResult> {
  const { entity, abVersion, buildTarget, cdnBucket } = params
  // S3 HEAD is cheap and non-blocking; 50 saturates the probe phase for typical
  // scenes (dozens of assets) without exhausting the default HTTPS agent pool.
  const concurrency = params.concurrency ?? 50
  const redisTtlSeconds = params.redisTtlSeconds ?? DEFAULT_REDIS_HIT_CACHE_TTL_SECONDS
  const logger = components.logs.getLogger('AssetReuse')

  let depsDigestByHash: ReadonlyMap<string, string>
  if (params.depsDigestByHash) {
    depsDigestByHash = params.depsDigestByHash
  } else {
    if (!params.contentServerUrl) {
      throw new Error('checkAssetCache: either depsDigestByHash or contentServerUrl must be supplied')
    }
    // Fallback path — used by tests and any caller that hasn't yet wired in
    // the per-asset digest pre-compute. Probe correctness is preserved
    // (skipped glbs aren't in `digests`, the probe loop below excludes
    // glb/gltf hashes missing from the digest map, so skipped hashes land
    // in neither `cachedHashes` nor `missingHashes`). What is NOT preserved
    // is observability: `result.skipped` is dropped here, so callers using
    // this branch get no signal about WHY a glb wasn't probed. The
    // production path in `executeConversion` always passes
    // `depsDigestByHash` explicitly and tracks `skipped` from its own
    // `computePerAssetDigests` call — that's the path that emits the warn
    // log + `ab_converter_glb_skipped_total` counter. New callers should
    // follow the production pattern rather than relying on this fallback.
    //
    // We deliberately do NOT plumb redis / metrics / logger through here.
    // The component-aware plumbing for `computePerAssetDigests` lives in
    // `scenes/component.ts`'s wrapper — that's the single place that
    // wires the URI cache, metric labels, and logger. Duplicating that
    // here would create two callers that need to stay in sync; the
    // fallback gets correct results, just no URI cache benefit. If
    // tests need the cache, they should go through the scenes component
    // wrapper.
    const result = await computePerAssetDigests(entity, params.contentServerUrl, { fetcher: params.fetcher })
    depsDigestByHash = result.digests
  }

  // Computed once per probe call so the loop below can `Set.has` rather than
  // re-walking regex patterns + metadata fields for every content entry, and
  // returned on `AssetCacheResult.metadataOnlyHashes` so `executeConversion`
  // can union it into the `-skippedHashes` flag passed to Unity without
  // re-deriving from the entity.
  const metadataOnlyHashes = findMetadataOnlyHashes(entity.content, entity.metadata)

  type Probe = { hash: string; skippable: boolean; filename: string; key: string }
  const seen = new Set<string>()
  const probes: Probe[] = []
  for (const entry of entity.content ?? []) {
    const ext = fileExtension(entry.file)
    // Probe only the file kinds Unity actually emits as their own asset
    // bundle — glb/gltf and textures. `.bin` is excluded because Unity
    // inlines buffers into their referencing GLTF's bundle rather than
    // producing a standalone `{hash}_{target}` object, so probing would
    // always miss and permanently block the full-cache short-circuit.
    if (!PROBE_EXTENSIONS.has(ext)) continue
    // Files referenced as raw-byte metadata (e.g. SDK-generated thumbnail
    // captured per deploy, navmap thumbnail field in scene.json) are read
    // directly from the content server by the launcher / world map UI —
    // Unity bundles built for them are dead artifacts and their hashes are
    // per-deploy unique, so probing always misses. Skip them entirely from
    // the probe so they don't pollute `cachedHashes` / `missingHashes`.
    if (metadataOnlyHashes.has(entry.hash)) continue
    // Glbs/gltfs that the digest computation marked as broken (missing deps
    // or unparseable bytes) won't ever be converted. Skip them from the
    // probe so they appear in neither `cachedHashes` nor `missingHashes` —
    // the canonical bundle they'd point at can't exist (Unity won't produce
    // it), and counting them as a miss would force a Unity run for a scene
    // whose remaining assets might all be cached.
    if (GLTF_EXTENSIONS_SET.has(ext) && !depsDigestByHash.has(entry.hash)) continue
    if (seen.has(entry.hash)) continue
    seen.add(entry.hash)
    const filename = canonicalFilenameForAsset(entry.hash, ext, buildTarget, depsDigestByHash)
    probes.push({
      hash: entry.hash,
      skippable: UNITY_SKIPPABLE_EXTENSIONS.has(ext),
      filename,
      key: `${abVersion}/assets/${filename}`
    })
  }

  if (probes.length === 0) {
    return {
      cachedHashes: [],
      missingHashes: [],
      unitySkippableHashes: [],
      canonicalNameByHash: {},
      depsDigestByHash,
      metadataOnlyHashes
    }
  }

  // Per-probe: check Redis first, fall through to S3 HEAD on miss. Redis errors
  // are swallowed and counted as misses inside `safeRedisHit`, so a transient
  // Redis outage degrades gracefully to "do S3 HEAD" rather than failing the
  // probe. On an S3 HEAD hit we write the key back to Redis fire-and-forget so
  // the next probe (here or on a peer pod) finds it cached.
  let cacheHitCount = 0
  let headHitCount = 0
  const hits = await mapBounded(
    probes.map((_, i) => i),
    concurrency,
    async (i): Promise<boolean> => {
      if (await safeRedisHit(components.redis, probes[i].key, logger, components.metrics)) {
        cacheHitCount++
        return true
      }
      const exists = await headExists(components.cdnS3, cdnBucket, probes[i].key)
      if (exists) {
        headHitCount++
        void safeRedisSet(components.redis, probes[i].key, redisTtlSeconds, logger, components.metrics)
      }
      return exists
    }
  )
  const headRequestCount = probes.length - cacheHitCount

  if (cacheHitCount > 0) {
    components.metrics.increment(
      'ab_converter_asset_probe_hit_cache_total',
      { build_target: buildTarget, ab_version: abVersion },
      cacheHitCount
    )
  }
  if (headRequestCount > 0) {
    components.metrics.increment(
      'ab_converter_asset_probe_head_total',
      { build_target: buildTarget, ab_version: abVersion },
      headRequestCount
    )
  }

  const cachedHashes: string[] = []
  const missingHashes: string[] = []
  const unitySkippableHashes: string[] = []
  const canonicalNameByHash: Record<string, string> = {}

  for (let i = 0; i < probes.length; i++) {
    const { hash, skippable, filename } = probes[i]
    canonicalNameByHash[hash] = filename
    if (hits[i]) {
      cachedHashes.push(hash)
      if (skippable) unitySkippableHashes.push(hash)
    } else {
      missingHashes.push(hash)
    }
  }

  components.metrics.increment(
    'ab_converter_asset_cache_hits_total',
    { build_target: buildTarget, ab_version: abVersion },
    cachedHashes.length
  )
  components.metrics.increment(
    'ab_converter_asset_cache_misses_total',
    { build_target: buildTarget, ab_version: abVersion },
    missingHashes.length
  )

  logger.info('Asset cache probe complete', {
    total: probes.length,
    cached: cachedHashes.length,
    missing: missingHashes.length,
    unitySkippable: unitySkippableHashes.length,
    // Number of content entries the probe loop excluded as metadata-only
    // (SDK thumbnail / navmap field). Exposed so `total` makes sense at a
    // glance — without this, a sudden drop in `total` across deploys would
    // be unexplained when in fact it reflects the metadata-only filter
    // kicking in for scenes that previously paid for a wasted Unity build.
    metadataOnly: metadataOnlyHashes.size,
    hitCacheServed: cacheHitCount,
    headRequests: headRequestCount,
    headHits: headHitCount,
    gltfAssetsDigested: depsDigestByHash.size
  } as any)

  return {
    cachedHashes,
    missingHashes,
    unitySkippableHashes,
    canonicalNameByHash,
    depsDigestByHash,
    metadataOnlyHashes
  }
}

/**
 * Remove files whose hash is already canonicalized from the local output directory
 * so the existing `uploadDir` matcher uploads only new bundles. A file is considered
 * to belong to a cached hash when it is exactly the hash, or when its leading
 * `{hash}` segment (before the first `_` or `.`) is in `cachedHashes`. Runs in
 * O(entries + hashes) via a Set lookup on the extracted prefix.
 */
export async function purgeCachedBundlesFromOutput(
  outDirectory: string,
  cachedHashes: string[],
  logger: ILoggerComponent.ILogger
): Promise<number> {
  if (cachedHashes.length === 0) return 0
  const cached = new Set(cachedHashes)
  let entries: string[]
  try {
    entries = await fs.readdir(outDirectory)
  } catch {
    return 0
  }

  const toUnlink: string[] = []
  for (const entry of entries) {
    if (!cached.has(entry) && !cached.has(extractHashFromBundleName(entry) ?? '')) continue
    toUnlink.push(entry)
  }

  // Parallel unlink with a concurrency cap. Scenes with hundreds of cached assets
  // could otherwise fire that many simultaneous syscalls and hit ENFILE on
  // low-ulimit containers; 50 mirrors the S3 HEAD probe concurrency.
  const results = await mapBounded(toUnlink, 50, async (entry) => {
    try {
      await fs.unlink(path.join(outDirectory, entry))
      return true
    } catch (err: any) {
      logger.warn(`Failed to purge cached bundle ${entry}: ${err.message}`)
      return false
    }
  })

  return results.filter(Boolean).length
}
