name: node

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: consumer-server/package-lock.json
      - name: install
        run: npm ci
        working-directory: consumer-server
      - name: build
        run: npm run build
        working-directory: consumer-server
      - name: test
        run: npm run test
        working-directory: consumer-server
