name: CI/CD on PR

on:
  pull_request:

jobs:
  pr:
    # TODO: restore full matrix (webgl + windows + mac) before merging
    strategy:
      matrix:
        include:
          - unity-docker-image: unityci/editor:6000.2.6f2-webgl-3
            service-name: asset-bundle-converter
            platform-target: webgl

    uses: ./.github/workflows/docker-common.yml
    with:
      service-name: ${{ matrix.service-name }}
      unity-docker-image: ${{ matrix.unity-docker-image }}
      platform-target: ${{ matrix.platform-target }}
      upload-image: false
      docker-tag: pr-${{ github.event.number }}
    secrets: inherit
